version: '3.1'

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        environment:
            # Секретный ключ для проверки клиентского токена
            AUTH_PRIVATE_KEY: f91eb2d2-c8d5-4cef-9b25-fec0e7b06882
            # Токен доступа к серверу авторизации
            AUTH_SERVER_API_KEY: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2MTE3NDM4MTMsImV4cCI6MTY0MzI3OTgxMywiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSJ9.ceBR9Q3IKlGaFjBxAvJmeZ2UaOXhK5A2miMfcC2HwyY
            # Server Port
            PORT: 8089
            # Swagger Doc Path
            SWAGGER_ROUTE: /docs
            # RefServer
            REF_SERVER_HOST: http://192.168.8.110:8080
            # RefServer
            EVO_CLOUD_HOST: http://192.168.8.110:8080
        ports:
            - 8089:8089
